.github/workflows/push-master.yaml

Adds codecov based test coverage reporting
Adds codecov based test coverage reporting
Test coverage

build: add codecov test coverage reporting

---

sample/package.json
sample/src/index.ts
sample/yarn.lock

Bumps the sample to use the latest release package version, simplifies the usage of the signature and proof suite.
Keeps samples up to date

feat: update sample

---

package.json

Updates the fields related to the published package on NPM
Maintenance on package setup

docs: update package publishing related fields in package json

---

CHANGELOG.md

Amend links in changelog
Changelog clarity

docs: fix-up changelog

---

docs/RELEASE.md

Updates documentation around the release process to use the rebase strategy to preserve generated tags
Documentation

docs: update release process

---

README.md
sample/package.json
sample/src/data/keyPair.json
sample/yarn.lock

Updates the sample to use the latest package version and adds an npm version badge to the repo
Library usage clarity

Sample updates

---

README.md

Updates the docs to reference the draft digital signature specification
Documentation

docs: update doc references

---

README.md
SECURITY.md

Adds a security policy
Defines the proper way for security researchers to responsible disclose security bugs and vulnerabilities

docs: adds Mattr's security policy

---

tsconfig.json

Removes copying the tests through into the output directory, was creating issues around the compiled package.
Fixed package consumption issue

build: fix tsc build output directory structure

---

src/types/CanonizeOptions.ts
src/types/CreateProofOptions.ts
src/types/CreateVerifyDataOptions.ts
src/types/DeriveProofOptions.ts
src/types/GetTypeOptions.ts
src/types/SignatureSuiteOptions.ts
src/types/SuiteSignOptions.ts
src/types/VerifyProofOptions.ts
src/types/VerifySignatureOptions.ts

Changes the types of the document loader and expansion map to enable better consumption with typed upstream libraries

refactor: documentLoader and expansionMap types

---

sample/package.json
sample/src/data/deriveProofFrame.json
sample/src/data/inputDocument.json
sample/src/data/lds-bbsbls2020-v0.0.json
sample/src/index.ts
sample/yarn.lock

Updates the sample to use the v0.7.0 release of jsonld-signatures-bbs
Keep the samples up to date 
Fixes #79, #70

feat(sample): update to v0.7.0 release

---

.github/workflows/push-master.yaml
.github/workflows/push-release.yaml

Changes the approach to injection of the NPMJS secret into the required github actions
CI maintenance

ci(github-actions): change npmjs authentication setup

---

src/BbsBlsSignatureProof2020.ts

When using `rn-bbs-signature` library this method will not work because it returns a promise.

fix: update blsCreateProof expected response to promise

---

src/BbsBlsSignatureProof2020.ts
src/deriveProof.ts

Adding missing nonce parameter

feat: add nonce parameter to deriveProof method

---

__tests__/BbsBlsSignature2020.spec.ts
__tests__/BbsBlsSignatureProof2020.spec.ts

Improves the test coverage of the API by adding in more tests for negative test cases
Test coverage

test: improve coverage with more negative test cases

---

jest.config.js
package.json
src/BbsBlsSignatureProof2020.ts
yarn.lock

Migrates to using the new async api for BBS+

feat: migrate to async api

---

package.json
yarn.lock

Bumps the version of two key dependencies to the latest stable releases

feat: bump bbs-signatures package version

---

sample/README.md
sample/package.json
sample/src/data/bbs.json
sample/src/data/deriveProofFrame.json
sample/src/data/inputDocument.json
sample/src/data/securityv3.json
sample/src/demo_multi.ts
sample/src/demo_single.ts
sample/yarn.lock

This updates the samples to show how to derive a proof from a document with multiple supported proofs which is related to issue #79

chore: updates samples to also show how to use multiple proofs

---

sample/src/demo_single.ts

This will help the community when they first experience this repository.
This PR does not introduce a breaking change.

refactor(sample): code example in the demo logs the wrong variable

---

__tests__/__fixtures__/contexts/bbs.json
__tests__/__fixtures__/contexts/schemaOrg.json
__tests__/__fixtures__/customDocumentLoader.ts

This updates the local document loader use for executing tests to cache all the required documents locally.
See above

test: update local document loader to cache all docs

---

.github/workflows/any-pr.yaml
.github/workflows/push-master.yaml
.github/workflows/push-release.yaml
package.json
yarn.lock

Bumps to the latest version of BBS signatures
Resolves #119 
Resolves #102
See above
Deprecates support for node 10

feat: bump bbs-signatures dependency

---

.github/workflows/any-pr.yaml
__tests__/__fixtures__/contexts/jws.json
__tests__/__fixtures__/customDocumentLoader.ts
__tests__/__fixtures__/data/did_example_82612387612873.json
__tests__/__fixtures__/data/did_example_82612387612873_test.json
__tests__/__fixtures__/data/test_signed_vc_jwk.json
__tests__/__fixtures__/data/test_vc_reveal_document_jwk.json
__tests__/__fixtures__/index.ts
__tests__/deriveProof.spec.ts
package.json
src/BbsBlsSignatureProof2020.ts
src/types/DidDocumentPublicKey.ts
src/types/JsonWebKey.ts
src/types/index.ts
yarn.lock

feat: allow the use of publicKeyJwk to derive and verify proof

---

package.json
yarn.lock

The main purpose of this PR is to use the latest version of bbs-signatures library that don't have known vulnerabilities

chore: bump up bbs-signatures dependency

---

package.json
yarn.lock

feat: update bls12381 dependency

---

CHANGELOG.md
docs/RELEASE.md
package.json

* release 1.0.0
* added release commands
* remove prefix `v` on tags
```
➜ jsonld-signatures-bbs git:(kh/release-1.0.0) git push origin --tags
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 170 bytes | 170.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0)
To github.com:mattrglobal/jsonld-signatures-bbs.git
* [new tag]         0.1.0 -> 0.1.0
* [new tag]         0.10.0 -> 0.10.0
* [new tag]         0.11.0 -> 0.11.0
* [new tag]         0.12.0 -> 0.12.0
* [new tag]         0.2.0 -> 0.2.0
* [new tag]         0.3.0 -> 0.3.0
* [new tag]         0.4.0 -> 0.4.0
* [new tag]         0.5.0 -> 0.5.0
* [new tag]         0.6.0 -> 0.6.0
* [new tag]         0.7.0 -> 0.7.0
* [new tag]         0.8.0 -> 0.8.0
* [new tag]         0.9.0 -> 0.9.0
* [new tag] …
```

release 1.0.0

---

.github/workflows/any-pr.yaml
.husky/commit-msg
.husky/pre-commit
__tests__/AnonymousVC.spec.ts
__tests__/BbsBlsSignature2020.spec.ts
__tests__/BbsBlsSignatureProof2020.spec.ts
__tests__/__fixtures__/customDocumentLoader.ts
__tests__/__fixtures__/index.ts
__tests__/deriveProof.spec.ts
__tests__/getProofs.spec.ts
__tests__/vc-js.spec.ts
commitlint.config.js
package.json
sample/ts-node/src/demo_multi.ts
sample/ts-node/src/demo_single.ts
src/BbsBlsSignature2020.ts
src/BbsBlsSignatureProof2020.ts
src/deriveProof.ts
src/types/JsonWebKey.ts
src/utilities.ts
yarn.lock

Jest & typescript upgrade.
Resolute node-forge version to 1.3.0 in several libs.
Resolute lodash version
Samples app audit fix will be in another pr once this fix version is published. 
Audit result after changes:
```
6 vulnerabilities found - Packages audited: 815
Severity: 3 Low | 3 Moderate
```

build(deps)!: update deps to fix audit security issues

---

.github/workflows/push-master.yaml
.github/workflows/push-release.yaml

ci: bump workflow node versions

---

sample/browser/data/suiteContext.json
sample/browser/index.web-sample.js
sample/browser/package.json
sample/browser/webpack.config.js
sample/browser/yarn.lock
sample/ts-node/package.json
sample/ts-node/src/data/suiteContext.json
sample/ts-node/src/demo_multi.ts
sample/ts-node/src/demo_single.ts
sample/ts-node/yarn.lock

[DXM-520](https://mattrglobal.atlassian.net/browse/DXM-520)

build(deps): fix sample audit issues

---

.github/workflows/push-master.yaml
.github/workflows/push-release.yaml

build: update npm token in cd workflow

---

.github/workflows/push-master.yaml
.github/workflows/push-release.yaml
scripts/publish.sh
scripts/publish_unstable.sh

- Fail the workflow job when script encounter error
- Only run one job in a specific Node.js version for publishing pacakge

ci: fix npm publish workflow

---

.github/workflows/any-pr.yaml
package.json

This PR adds a dependency license check to be run on every PR.
This PR adds a dependency license check to be run on every PR.
**[contributing](https://github.com/mattrglobal/docs-engineering/blob/master/process/CONTRIBUTING.md)** document.
[TCM-219](https://mattrglobal.atlassian.net/browse/TCM-219)

chore: add dependency license check

---

sample/browser/package.json
sample/ts-node/package.json

Update samples to resolve vulnerability with xmldom

build: update samples
